export default [
  // [/http:\/\/www\.xiaojian\.me/g, 'https://www.guorenbao.com'],
  // [/www\.xiaojian\.me/g, 'www.guorenbao.com'],
  // [/http:\/\/marketing\.xiaojian\.me/g,'https://www.guorenbao.com/pclp'],
  // [/\/\/gopendpoint\.treespaper\.com/g, 'https://endpoint.guorenbao.com'],
  // [/\/\/goopal\.xiaojian\.me/g, 'https://endpoint.guorenbao.com'],
  // [/activity\.xiaojian\.me/g, 'huodong.objectonly.com'],
  // [/app\.xiaojian\.me/g, 'app.objectonly.cn'],
  // [/wxe91980c4944999fe/g, 'wx55923db8dfb94e44'],
  // [/wx675e32b0765061ba/g, 'wx55923db8dfb94e44'],
  // [/\/\/172\.16\.33\.10:8089/g, 'https://track.guorenbao.com'],
  // [/http:\/\/exchange\.treespaper\.com\/auth\//g, 'https://www.bicooo.com/auth/'],
  // [/\/\/exchange\.xiaojian\.me/g, 'https://www.bicooo.com'],

  // [/http:\/\/www\.goopal1\.com/g, 'https://www.guorenbao.com'],
  // [/www\.goopal1\.com/g, 'www.guorenbao.com'],
  // [/http:\/\/marketing\.goopal1\.com/g,'https://www.guorenbao.com/pclp'],
  // [/\/\/gopendpoint\.treespaper\.com/g, 'https://endpoint.guorenbao.com'],
  // [/\/\/goopal\.goopal1\.com/g, 'https://endpoint.guorenbao.com'],
  // [/activity\.goopal1\.com/g, 'huodong.objectonly.com'],
  // [/app\.goopal1\.com/g, 'app.objectonly.cn'],
  // [/wxe91980c4944999fe/g, 'wx55923db8dfb94e44'],
  // [/wx675e32b0765061ba/g, 'wx55923db8dfb94e44'],
  // [/\/\/172\.16\.33\.10:8089/g, 'https://track.guorenbao.com'],
  // [/http:\/\/exchange\.treespaper\.com\/auth\//g, 'https://www.bicooo.com/auth/'],
  // [/\/\/exchange\.goopal1\.com/g, 'https://www.bicooo.com'],
  // [/1260054327/g, '1259998164'],

  
  [/http:\/\/chat\.wanlefu\.com\/slx-account-web/g, 'http://abtestaccount.wanlefu.com/slx-account-web'],
  [/http:\/\/chat\.wanlefu\.com\/slx-loan-web/g, 'http://abtestloan.wanlefu.com/slx-loan-web'],
  [/chat\.wanlefu\.com\/slx-account-web/g, 'abtestaccount.wanlefu.com/slx-account-web'],
  [/chat\.wanlefu\.com\/slx-loan-web/g, 'abtestloan.wanlefu.com/slx-loan-web'],
]
